services:
  - type: web
    name: aussd-school-portal
    runtime: image
    repo: https://github.com/hkipfrosting/aussd-school-portal
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
